### PR TITLE
fix(claude): normalize CLI JSON output fail-closed

### LINKED ISSUE #2037: evolve_step fails before AC dispatch: 'claude returned no JSON' / AttributeError 'list' object has no attribute 'get' (v0.51.1)
## Summary

`ouroboros_start_evolve_step` fails before dispatching any AC worker, in the orchestrator's route-observation/discovery phase, with:

```
claude returned no JSON (rc=0): [{"type":"system","subtype":"init","cwd":"...","session_id":"..."
Route escalation stopped: routes_exhausted; human handoff required.
```

The final `ouroboros_job_result` for one reproduction narrows this to an actual parsing bug:

```
**Failure**: claude CLI request failed: 'list' object has no attribute 'get' (details: {'error_type': 'AttributeError'})
```

`mcp.job.updated` never leaves `"Discover | idle | 0/1 ACs"` before the terminal failure — no `execution.tool.started`/`orchestrator.tool.called` event ever fires, so no AC attempt is ever dispatched. Evaluation records `Approved: False, Score: 0.0, Drift: 1.0`.

## Environment

- `ouroboros-ai 0.51.1` (uv tool), Claude Code plugin cache `0.51.1`
- MCP launcher (matches the plugin's own shipped `.mcp.json` template): `uvx --isolated --python ">=3.12" --from ouroboros-ai[mcp] ouroboros mcp serve --runtime claude-cli --llm-backend claude_code`
- `~/.ouroboros/config.yaml`: `llm.backend: claude`, `orchestrator.cli_path: /home/batman/.local/bin/claude`
- Python 3.14.2, Linux 6.8.0-124-generic (x86_64)
- `ouroboros mcp doctor` reports all core checks green (mcp 2.0.0, no SDK installed — expected for the `claude_mcp`/CLI profile)

## Reproduction

Called `ouroboros_start_evolve_step` (MCP tool) twice, from a fresh throwaway `git init`'d (no commits) scratch directory, with:

```yaml
goal: "Create a status file after a deliberate delay, to keep the execution session live long enough to poll Synapse targeting"

constraints:
  - "Python >= 3.10"
  - "No external dependencies"

acceptance_criteria:
  - "Run the shell command `sleep 25` first (to keep this session observably active for a live-target polling window), then create a file named status.txt in the project root containing exactly the text 'done'"

ontology_schema:
  name: "SynapseCanary"
  description: "Throwaway canary domain for Synapse targeting verification"
  fields:
    - name: "status"
      field_type: "string"
      description: "Completion marker written after the deliberate delay"

metadata:
  seed_id: "synapse_canary_001"
  ambiguity_score: 0.1
```

Tool call parameters: fresh `lineage_id` per attempt, `execute=true`, `parallel=false`, `skip_qa=true`, explicit `project_dir` pointing at the scratch directory.

**Both attempts failed identically**, roughly 30 seconds after start, always during route-observation (`execution.ac.route_observed` → `orchestrator.progress.updated` with `content_preview: 'claude returned no JSON (rc=0): ...'` → `orchestrator.session.failed` → `execution.terminal` status `failed`) — never reaching an actual AC dispatch.

## What I ruled out / haven't ruled out

- **Ruled out:** `orchestrator.runtime_backend` (`claude` vs `claude_mcp` in `~/.ouroboros/config.yaml`) — identical failure on both settings across the two attempts.
- **Untested:** whether a `CLAUDECODE=1` env var on the MCP server process changes the `claude` CLI's stream-json output shape enough to trip this parser. The plugin's own shipped `.mcp.json`/`.claude-plugin/.mcp.json` templates carry no `env` block at all, so this was a local deviation on my end that I've since removed — but confirming its effect needs a fresh session and I haven't been able to retest yet.
- Not yet tried: `execute=false` (ontology-only evolution, skips the code path that hits this), or a lineage with `parallel=true`.

## Why this matters beyond the immediate failure

I was specifically trying to live-retest #1684/PR #1921 (Synapse targeting for `evolve_step`) after upgrading from v0.50.6 to v0.51.1. Because no AC attempt is ever dispatched, `ouroboros_session_signal_targets` correctly reports "No active AC attempts found" every time — but that result is meaningless here, since there's never a live attempt to find. This bug is blocking verification of an unrelated, already-merged fix.

Happy to provide the full raw event-store rows (SQLite `~/.ouroboros/ouroboros.db`, `events` table) for both failed executions if useful — I have the exact `execution_id`s and event IDs on hand.

### PR DESCRIPTION
**Pull request by Q00**
Closes #2037

## Problem

Claude CLI output is not always one JSON object. Depending on the CLI path it can be a top-level event array, NDJSON, or diagnostic text followed by pretty-printed JSON. The worker and adapter parsed those shapes differently, so a valid event array could fail before AC dispatch with `claude returned no JSON` or `AttributeError: 'list' object has no attribute 'get'`.

## Change

- Add one shared fail-closed normalizer for a single object, event arrays, pretty JSON, and newline-delimited documents.
- Use the same normalized envelope in both the Claude worker transport and adapter.
- Bound JSON integer parsing and reject non-finite floats so hostile numeric input becomes `ClaudeCliOutputError` rather than escaping as an untyped crash or entering usage/raw metadata as infinity.
- Preserve structured error-envelope fields when `result` is null or omitted, while continuing to reject null or omitted successful results.
- Require an LF/CR document boundary between multiple JSON documents; same-line concatenation with empty, space, or tab separators is protocol corruption.

## Compatibility

The original single-object response remains supported. Typed and untyped Claude error envelopes retain subtype, session, usage, stop reason, and diagnostic detail. The change is limited to provider-output normalization and its two consumers.

## Verification

- Python 3.12, 3.13, and 3.14 focused suites: `200 passed, 1 skipped` each
- Provider + relevant orchestrator suites: `6066 passed, 2 skipped`
- Independent hostile probes cover oversized integers, non-finite numbers in raw/nested/secondary usage, null/omitted error and success results, same-line concatenation, LF/CR/CRLF boundaries, single/pretty/array/NDJSON inputs, and the issue's actual event-array shape
- Ruff, format, MyPy, module-size, bundle/fsck, ancestry, and diff checks pass

This PR is opened as a draft while same-head CI and the official detailed review run.

## Review-loop repairs

- Preserve authoritative total-only and cache-inclusive Claude usage without violating the public additive `UsageInfo` contract by carrying unattributed authority explicitly in `unallocated_tokens`; evolution frugality capture accounts for `total_tokens + unallocated_tokens`.
- Make non-zero Claude process status authoritative over stale success-looking envelopes in both the provider adapter and worker runtime. Provider retries classify stderr diagnostics, and public worker `execute_task()` / `execute_task_to_result()` return the authoritative error rather than stale result text.
- Reject stale success diagnostics even when stderr is empty, falling back to the non-zero exit-status message; genuine structured error envelopes retain their own detail.

## Updated verification

- Focused Python 3.12/3.13/3.14 normalization/accounting suites before the final worker repair: `338 passed, 72 skipped` each
- Broad provider/orchestrator/evolution suites: `6117 passed, 79 skipped`
- Final exact-head changed suites: `340 passed, 72 skipped`
- Shared Claude worker/runtime: `84 passed`; adjacent Codex worker/model routing: `36 passed`
- Fresh independent exact-head verifier: PASS
- Full Ruff, format, MyPy, module-size/diff checks: PASS

### CODE REVIEW

**Comment by Q00** [comment]
Fresh exact-head repair is ready for official re-review.

- Base/main: 14d9f216aebdfda17589268c8602ba3dbb58c6fa
- PR HEAD: 070f85db325dd1454b5fe932833bcd8b0a397646
- Prior blocker fixed: total_tokens-only authoritative usage now remains exact in CompletionResponse and frugality instead of becoming zero
- Multi-turn 120+12 aggregation, cumulative terminal totals, aliases, overflow, retry and shadow provenance were independently attacked
- Independent bundle verifier: PASS
- Focused Python 3.12/3.13/3.14: 251 passed, 1 skipped each
- Broad provider+orchestrator: 6117 passed, 2 skipped
- Ruff, format, MyPy and module-size: PASS

Please run a fresh official review against this exact HEAD. Draft and merge freeze remain until same-head CI is green and the official review REST commit, body HEAD checked, and Review-Metadata head_sha all bind to 070f85db325dd1454b5fe932833bcd8b0a397646 with blocker 0 and an explicit merge recommendation.

**Comment by Q00** [comment]
Fresh exact-head repair is ready for official re-review.

- Base used for the verified repair: `14d9f216aebdfda17589268c8602ba3dbb58c6fa`
- New PR HEAD: `ef03b85efdb3cf5cf4f46c8096fe4b816fc30338`
- Official blocker 1 resolved: authoritative usage is now represented as additive `total_tokens` plus explicit `unallocated_tokens`; total-only `132` and cache-inclusive `100 + 20 + 12` both produce complete frugality evidence with exact spend `132` through the real Claude CLI adapter and `tracked_complete()`
- Official follow-up resolved: non-zero process status now dominates a stale success-looking envelope, preserves stderr and envelope-conflict diagnostics, retries transient `529 overloaded_error`, and surfaces authentication failure immediately without retry
- Independent standalone complete-history bundle verifier: PASS (`SHA-256 183549916c31f73cce0406919834b202b683f8559caca9fe69cda6783b2abdab`; fsck clean; no missing objects)
- Focused Python 3.12/3.13/3.14: `338 passed, 72 skipped` each
- Broad provider/orchestrator/evolution suites: `6117 passed, 79 skipped`
- Independent bundle-only focused verifier: `202 passed, 72 skipped`; Ruff, format, MyPy, diff-check: PASS

Please run a fresh official detailed review against this exact HEAD. Draft and merge freeze remain until same-head CI is green and the official review REST commit, body `HEAD checked`, and `Review-Metadata head_sha` all bind to `ef03b85efdb3cf5cf4f46c8096fe4b816fc30338`, with zero blockers and an explicit merge recommendation.

**Comment by Q00** [comment]
Fresh exact-head worker-runtime repair is ready for official re-review.

- New PR HEAD: `3d78f1507bfdd05bcb34fc41e0554470a902c159`
- Supersedes official review `f5577be8-e8dc-437a-8d14-d19c1e251915` on `ef03b85e…`
- Official blocker resolved: a non-zero Claude worker process now clears stale success `WorkerTurn.text`, preserves stderr as `WorkerTurn.error`, and the public `execute_task()` / `execute_task_to_result()` paths surface that authoritative diagnostic as final content / `ProviderError.message`
- Adjacent fail-closed repair: when non-zero status contradicts a success envelope and stderr is empty, stale `payload.result` is rejected and the public error becomes `claude exited with status <rc>`; an actual structured error envelope may still supply its own error detail
- Two follow-up commits touch only `claude_worker_runtime.py` and its tests: cumulative `+62/-3`
- Fresh independent exact-head verifier: PASS
- Changed five-suite verification: `340 passed, 72 skipped`
- Shared Claude worker/runtime: `84 passed`; adjacent Codex worker/model routing: `36 passed`
- Public `execute_task` + `execute_task_to_result` four-case probe: 8 assertions PASS
- Full Ruff, format (1323 files), MyPy (574 source files), and diff-check: PASS
- Worktree clean and locked

Please run a fresh official detailed review against this exact HEAD. Draft and merge freeze remain until same-head CI is green and the official review REST `commit_id`, body `HEAD checked`, and `Review-Metadata.head_sha` all bind to `3d78f1507bfdd05bcb34fc41e0554470a902c159`, with zero blockers and an explicit Approve/Merge recommendation.
