### PR TITLE
feat(evaluation): enforce seed contracts across checks

### PR DESCRIPTION
**Pull request by Q00**
## Summary

- Builds on #495 by carrying SeedContract into semantic, consensus, evaluate, QA, subagent, and Ralph/evolution paths.
- Adds a Seed contract audit gate for goal alignment, drift, uncertainty, and reward-hacking risk so mechanical AC passes are necessary but not sufficient.
- Preserves non-code task intent by extracting `task_type` and evaluating research/analysis outputs as documents instead of code.

## Changes

- Add `contract_audit_failure()` and use it in Ralph/evolution semantic approval.
- Thread `SeedContract` through evaluation contexts, consensus prompts, MCP evaluate, delegated subagents, and post-run QA quality bars.
- Persist `seed_json` in sessions so later evaluation can reconstruct the Seed contract.
- Extract `TASK_TYPE` in seed generation and update seed-architect guidance.
- Skip code validation for non-code evolution tasks.
- Expand tests for semantic/consensus prompts, session restoration, quality bars, task type extraction, and contract audit thresholds.

## Notes

Stacked on #495. This PR still does not implement the later Idea/Origin-contract convergence refactor; it only enforces the SeedContract introduced by #495 across execution/evaluation paths.

### CODE REVIEW

**Review by Sathvik-1007 — APPROVED** [review]
Reviewed dc2e86d (and 244c419).

### 244c419 — tolerate malformed semantic audit fallback
Good fix. Soft fallback now catches `ValidationError` alongside `ProviderError`. When semantic evaluator itself breaks (malformed output, schema mismatch), no `SemanticResult` exists to audit — so crashing the evolution loop is wrong. Soft fallback with `error_type` logging is the right call.
Test proves: malformed evaluator → soft fallback → `final_approved=True`.
### dc2e86d — reject real semantic contract drift
Critical counterpart test. Mock returns valid `CompletionResponse` with `drift_score=0.8` (threshold 0.30). Proves contract audit gates reject real drift even when AC passes.
Together these two commits prove:
- Evaluator fails → soft fallback (resilience)
- Evaluator succeeds but drifts → hard reject (correctness)
Solid pair.
---

Reviewed dc2e86d (full PR, 8 commits). Contract threading is solid — SeedContract flows cleanly through semantic, consensus, QA, subagent, and evolution paths. contract_audit_failure() is a clean 6-gate design. The last two commits nail the resilience/correctness balance. Few things I noticed:

---
1. log.info metrics fire before seed hydration
evaluation_handlers.py:453 logs has_seed=seed_content is not None — but seed hydration from session happens at L461 (_load_seed_content_from_session). So any evaluation where the caller didn't pass seed_content explicitly logs has_seed=False even when the session has a persisted seed_json and hydration succeeds two lines later.
Means your metrics will undercount seed-aware evaluations. Easy fix: move the log.info block below L461, or add a second log after hydration with the corrected value.
---
2. JSON content wrapped in  `yaml `` fence
subagent.py:474 (and L712, L826, L1156) wraps seed_content in  `yaml ``:
seed_section = f"{contract_section}\n## Seed Specification\n```yaml\n{seed_content}\n```\n"
But seed_content comes from json.dumps(seed.to_dict()) — it's JSON ({"goal": "...", "constraints": [...]}), not YAML block style. JSON is technically valid YAML, so parsing won't break (yaml.safe_load handles it fine at L70). But the fence label is cosmetically misleading for anyone reading the rendered prompt.
Either change to  `json `` or convert to YAML block style before wrapping.
---
3. test_contract_audit.py covers 2 of 7 gate paths
contract_audit_failure() has 7 distinct paths: None guard, ac_compliance, score, goal_alignment, drift, uncertainty, reward_hacking. Unit tests only cover drift and reward_hacking (plus the all-pass case). Missing:
- result is None → "semantic evaluation did not run"
- ac_compliance=False → "acceptance criteria were not semantically satisfied"
- score < 0.80
- goal_alignment < 0.80
- uncertainty > 0.30
The integration test in dc2e86d covers drift through the full evolution pipeline, which is great. But the unit-level gates for the other 5 paths are unguarded — a threshold constant change or comparison flip would pass silently.
---
4. 244c419 — tolerate malformed semantic audit fallback
Good fix. Soft fallback now catches ValidationError alongside ProviderError. When semantic evaluator itself breaks (malformed output, schema mismatch), no SemanticResult exists to audit — so crashing the evolution loop is wrong. Soft fallback with error_type logging is the right call.
Test proves: malformed evaluator → soft fallback → final_approved=True.
---
5. dc2e86d — reject real semantic contract drift
Critical counterpart test. Mock returns valid CompletionResponse with drift_score=0.8 (threshold 0.30). Proves contract audit gates reject real drift even when AC passes.
Together with 244c419, these two commits prove:
- Evaluator fails → soft fallback (resilience)
- Evaluator succeeds but drifts → hard reject (correctness)
---
1-3 are polish. 4-5 are the reason for the approve. Nice work on the contract threading overall.
